(define run (lambda ()
                (term:setCursorPos 1 (term:getCursorY))
                (print "> ")
                (define input (gets ""))
                (cond ((null? input)
                       (println "null"))
                      ((string=? input "clear")
                       (term:clear)
                       (term:setCursorPos 1 1)
                       (println (string-append "KPC-OS " (os:version)))
                       (term:setCursorPos 1 2)
                       (print "> ")
                       (run))
                      (else
                          (term:setCursorPos 1 (+ (term:getCursorY) 1))
                          (define output (os:runScheme input))
                          (cond ((null? output)
                                 (term:setCursorPos 1 (+ (term:getCursorY) 1))
                                 (run))
                                (else
                                    (println output)
                                    (run)))))))
(term:clear)
(term:setCursorPos 1 1)
(println (string-append "KPC-OS " (os:version)))
(run)